stacker_bucket: oliviervg-cloudformation
sys_path: ./stacks/

stacks:
  - name: vpc
    class_path: vpc.VPC
    variables:
      VpcCidr: 10.0.0.0/16
      Tags:
        - Name: ${namespace}

  - name: subnets
    class_path: subnets.Subnets
    variables:
      VpcId: ${output vpc::VpcId}
      IgwId: ${output vpc::IgwId}
      Subnets:
        - Tier: public
          Type: public
          AZ: eu-west-2a
          Cidr: 10.0.0.0/24
          Tags:
            - Name: ${namespace}-public-eu-west-2a
        - Tier: public
          Type: public
          AZ: eu-west-2b
          Cidr: 10.0.1.0/24
          Tags:
            - Name: ${namespace}-public-eu-west-2b
        - Tier: private
          Type: private
          AZ: eu-west-2a
          Cidr: 10.0.2.0/24
          Tags:
            - Name: ${namespace}-private-eu-west-2a
        - Tier: private
          Type: private
          AZ: eu-west-2b
          Cidr: 10.0.3.0/24
          Tags:
            - Name: ${namespace}-private-eu-west-2b

  - name: s3-endpoint
    class_path: endpoint.Endpoint
    variables:
      VpcId: ${output vpc::VpcId}
      Service: s3
      RouteTableIds:
        - ${output subnets::PublicRouteTableId}
        - ${output subnets::PrivateRouteTableEuWest2aId}
        - ${output subnets::PrivateRouteTableEuWest2bId}

  - name: nat
    class_path: nat.NatGW
    enabled: false
    variables:
      PublicSubnetIds:
        - ${output subnets::PublicSubnetEuWest2aId}
        - ${output subnets::PublicSubnetEuWest2bId}
      PrivateRouteTableIds:
        - ${output subnets::PrivateRouteTableEuWest2aId}
        - ${output subnets::PrivateRouteTableEuWest2bId}
      HighAvailability: False
