stacker_bucket: oliviervg-cloudformation
sys_path: ./stacks/

stacks:
  - name: vpc
    class_path: vpc.VPC
    variables:
      VpcCidr: 10.0.0.0/16
      Tags:
        - Name: ${namespace}

  - name: subnets
    class_path: subnets.Subnets
    variables:
      VpcId: ${vpc::VpcId}
      IgwId: ${vpc::IgwId}
      Subnets:
        - Tier: web
          Type: public
          AZ: eu-west-2a
          Cidr: 10.0.0.0/24
          Tags:
            - Name: ${namespace}-public-web-eu-west-2a
        - Tier: web
          Type: public
          AZ: eu-west-2b
          Cidr: 10.0.1.0/24
          Tags:
            - Name: ${namespace}-public-web-eu-west-2b
        - Tier: app
          Type: private
          AZ: eu-west-2a
          Cidr: 10.0.2.0/24
          Tags:
            - Name: ${namespace}-private-app-eu-west-2a
        - Tier: app
          Type: private
          AZ: eu-west-2b
          Cidr: 10.0.3.0/24
          Tags:
            - Name: ${namespace}-private-app-eu-west-2b

  - name: s3-endpoint
    class_path: endpoint.Endpoint
    variables:
      VpcId: ${vpc::VpcId}
      Service: s3
      RouteTableIds:
        - ${subnets::WebRouteTableId}
        - ${subnets::AppRouteTableEuWest2aId}
        - ${subnets::AppRouteTableEuWest2bId}

  - name: nat
    class_path: nat.NatGW
    variables:
      PublicSubnetIds:
        - ${subnets::WebSubnetEuWest2aId}
        - ${subnets::WebSubnetEuWest2bId}
      PrivateRouteTableIds:
        - ${subnets::AppRouteTableEuWest2aId}
        - ${subnets::AppRouteTableEuWest2bId}
      HighAvailability: True
